server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tjumcw/springcloud.git
          search-paths: config
          username: tjumcw
          password: Miao970508
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/